services:
  # Serviço da API Backend (NestJS)
  backend:
    image: inf-att-backend-image
    container_name: inf_att-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/inf_att_db?schema=public
    depends_on:
      - db
    command: sh -c "npm install && npx prisma migrate deploy && npx prisma db seed && npm run start:dev"

  # Serviço da Interface Frontend (React/Vite)
  frontend:
    image: inf-att-frontend-image
    container_name: inf_att-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build
    ports:
      - "8080:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
 
  # Serviço do Banco de Dados (PostgreSQL)
  db:
    image: postgres:18
    container_name: inf_att-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=inf_att_db
      - PGTZ=America/Sao_Paulo
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5433:5432"

volumes:
  pgdata:
